### PR TITLE
Update OWL API and SLF4J

### PR DESCRIPTION
**Pull request by joephayes**
* Updates project version to 0.0.5
* Updates owlapi version to 5.1.12
* Updates slf4j version to 1.7.25
* Adds exclusion for maven invoker plugin - fixed logging version mismatch error I encountered when running CLI.
* Adds gitignore for target and generated files

Related to issue https://github.com/EcoStruxure/OLGA/issues/5

### CODE REVIEW

**Comment by charbull** [comment]
Thank you @joephayes !

**Comment by charbull** [comment]
Did this fixes the issue of the NPE for the OntologyDocumentLoader?

**Comment by joephayes** [comment]
Not sure but I am seeing a new error when I run the tests with the latest on master, which I did not see previously. 

```
java.lang.NoClassDefFoundError: Could not initialize class org.semanticweb.owlapi.model.IRI
        at semanticstore.ontology.library.generator.global.UTILSTest.testcleanPath(UTILSTest.java:37)

```

Do you see this error when you run the following:

```
 mvn clean install --projects OLGA-Core

```

@charbull @radissoa ?

**Comment by radissoa** [comment]
I don't see it... Have you tried cleaning your .m2/repository directory and relaunching the test, it may be some dependency mixup ?

**Comment by joephayes** [comment]
I tried that and I think the dependencies are now OK, but I saw some new errors. Let me dig through those and I'll open an issue if it is not something environmental on my end! Thanks!

**Pull request merged**
